accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView



app_name= 'accounts'

urlpatterns = [
    path('login/',auth_views.LoginView.as_view(template_name='accounts/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('Signup/',views.Signup.as_view(),name='signup'),
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]

group/urls.py
from django.urls import path
from . import views

app_name= 'group'

urlpatterns = [
    path('',views.ListGroups.as_view(),name='all'),
    path('new/',views.CreateGroup.as_view(),name='create'),
    path('posts/in/<slug>/',views.SingleGroup.as_view(),name='single'),
    path("join/<slug>/", views.JoinGroup.as_view(), name='join'),
    path("leave/<slug>/", views.LeaveGroup.as_view(), name='leave'),
]

simplesocial/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('',views.HomePage.as_view(),name='home'),
    path('admin/', admin.site.urls),
    path('test/',views.TestPage.as_view(),name='test'),
    path('thanks/',views.ThanksPage.as_view(),name='thanks'),
    path('accounts/',include("accounts.urls",namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('posts/', include('posts.urls',namespace='posts')),
    path('group/',include('group.urls',namespace='group'))


]
urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/master.css' %}">
    <link rel="stylesheet" href="{% static 'simplesocial/css/master.css'%}">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
</head>
<body>
<nav class="navbar navbar-expand-lg bg-dark mynav" role="navigation" id="navbar">
    <div class="container">
        <div class="navbar-nav align-items-center">
        <a class="navbar-brand mynav" href="{% url 'home' %}">Social Network</a>
        </div>

        {% if user.is_authenticated %}
            <a href="{% url 'posts:create' %}">Post</a>
            <a href="{% url 'group:all' %}">Groups</a>
            <a href="{% url 'group:create' %}">Create Groups</a>
            <a href="{% url 'accounts:logout' %}">Log out</a>
        {% else %}
            <a href="groups:all">Groups</a>
            <a href="{% url 'accounts:login' %}">Login</a>
            <a href="{% url 'accounts:signup' %}">sign up</a>
        {% endif %}

    </div>

</nav>
<div class="container mycontent">
{% block content %}
{% endblock %}
</div>
 <canvas id="canvas"></canvas>

    <script src="{% static "simplesocial/js/master.js"%}" type="text/javascript" ></script>

    <!-- Latest compiled and minified jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>

templates/index.html
{% extends "base.html" %}
{% block content %}


<h1>Welcome to Social Network!</h1>

{% endblock %}

templates/test.html
{% extends "base.html" %}
{% block content %}
<h1>You are logged in!</h1>

{% endblock %}

templates/thanks.html
{% extends "base.html" %}
{% block content %}
<h1>thanks for visiting</h1>

{% endblock %}